version: '3.8'

volumes:
  postgres: ~

services:
  calendar:
    container_name: ${APP_NAME}_calendar
    build:
      context: ..
      dockerfile: ./build/calendar/Dockerfile
    restart: on-failure
    networks:
      - new
    ports:
      - "8888:8888"
      - "50051:50051"
    command: --config /configs/config.json
    volumes:
      - "../configs:/configs"
    depends_on:
      - postgres

#  scheduler:
#    container_name: ${APP_NAME}_scheduler
#    build:
#      context: ..
#      dockerfile: ./build/scheduler/Dockerfile
#    restart: on-failure
#    command: --config /configs/config.json
#    volumes:
#      - "../configs:/configs"
#    depends_on:
#      - postgres
#      - rabbit
#
#  sender:
#    container_name: ${APP_NAME}_sender
#    build:
#      context: ..
#      dockerfile: ./build/sender/Dockerfile
#    restart: on-failure
#    command: --config /configs/config.json
#    volumes:
#      - "../configs:/configs"
#    depends_on:
#      - postgres
#      - rabbit

  postgres:
    image: postgres:alpine
    container_name: ${APP_NAME}_postgres
    networks:
      new:
        aliases:
          - database
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    restart: on-failure
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    container_name: ${APP_NAME}_migrate
    networks:
      - new
    volumes:
      - "../migrations:/migrations"
    command: [ "-path", "/migrations", "-database",  "postgres://go_user:go_password@database:5432/events_db?sslmode=disable", "up" ]
    links:
      - postgres

  rabbit:
    container_name: ${APP_NAME}_rabbit
    image: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
networks:
  new:



